name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache Tcl build
      id: cache-tcl
      uses: actions/cache@v3
      with:
        path: /opt/tcl8.7
        key: ${{ runner.os }}-f7629abff2

    - name: Build Tcl 8.7
      if: steps.cache-tcl.outputs.cache-hit != 'true'
      run: |
        mkdir -p /tmp/src/tcl
        cd /tmp/src/tcl
        wget https://core.tcl-lang.org/tcl/tarball/f7629abff2/tcl.tar.gz -O - | tar xz --strip-components=1
        cd unix
        ./configure --prefix=/opt/tcl8.7
        make -j 8
        sudo make install
        
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: autoconf
      run: autoconf
      
    - name: configure
      run: ./configure --with-tcl=/opt/tcl8.7/lib

    - name: Install dependencies
      run: make

    - name: Run check
      run: make test

